spring:
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://124.223.214.4:3306/user_center
    username: dogyupi
    password: yupi666
    # session失效时间
  session:
    timeout: 86400
server:
  address: 0.0.0.0
